# Generated by Django 5.2.6 on 2025-09-11 06:00

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='英文数字混合', max_length=16, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(16), accounts.validators.validate_username], verbose_name='账户名称'),
        ),
    ]
