# Generated by Django 5.2.6 on 2025-09-09 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='头像')),
                ('sex', models.CharField(choices=[('m', '男'), ('f', '女')], max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('education', models.CharField(blank=True, max_length=50, verbose_name='学历')),
                ('signature', models.CharField(max_length=100, verbose_name='个性签名')),
                ('hobby', models.CharField(blank=True, max_length=100, verbose_name='爱好')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
