"""
Django settings for user_web_server project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(64y5xx@-%d!=&4s6b8ex-k!$4wuyc-ku8p6sh3m+w&_ss@p$o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许的接收请求的主机：用户的请求到了这个server,Django会解析请求的host头，
# 要求host头必须是在下面的列表中，否则爆出异常 DisallowedHost
ALLOWED_HOSTS = [ # server部署机器的 IP
    'localhost', 
    '127.0.0.1',
    '192.168.0.102', 
    'a2.richudongfang1642.cn',
    '[::1]',          # IPv6 localhost
]


# Application definition

# 默认安装的app 都是Django提供的开箱即用的组件，非常方便
# 当你开发自己app模块时，也要添加到这里，才能呗Django感知到
INSTALLED_APPS = [
    'django.contrib.admin', #  提供 Django 自带的 后台管理界面
    'django.contrib.auth', #  用户认证系统
    'django.contrib.contenttypes', # 
    'django.contrib.sessions', # 会话管理
    'django.contrib.messages', # 消息框架
    'django.contrib.staticfiles', # 静态文件管理（CSS/JS/图片等）
    # 第三方auth模块，对支持用户认证支持非常完善
    'django.contrib.sites', # 因为django-allauth 需要使用site模型存储站点信息
    'allauth',
    'allauth.account',  # 这些app都是自带有自己的模板的，django都会自动导入
    'allauth.socialaccount',  #  requires install using `django-allauth[socialaccount]`.
    'allauth.socialaccount.providers.weixin', # include the providers you want to enable:
    
    # rest_framework框架，转为提供api风格的权限接口
    'rest_framework',  # DRF：提供 API 能力
    'rest_framework.authtoken',  # DRF 的 Token 认证支持
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'dj_rest_auth',  # 基于 DRF，提供 login/logout 接口
    'dj_rest_auth.registration', # 提供注册接口
    
    ###我们自己的app(app_name.apps.AppLearnConfig[apps.py里的类名])
    'app_learn',  # 学习app
    'accounts', # 用户管理app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # allauth模块的中间件
    "allauth.account.middleware.AccountMiddleware",
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # 使用 JWT
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # 要求所有API都开启登录验证
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    # access token 一旦签发，在过期前默认始终有效（除非加入黑名单）
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),   # Access Token（访问令牌）的有效期： 15后过期
    # 用户登录时获得的 refresh token 可以用来换取新的 access token，最长可用 14 天
    # 当 access token 过期后，客户端可以用 refresh token 向服务器请求一个新的 access token
    # refresh token 更敏感！一旦泄露，必须配合黑名单机制使用，才能实现“登出即失效”
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # 刷新Token有效期（可选）
    'ROTATE_REFRESH_TOKENS': True,
    # 每次使用 refresh token 换取新 token 后，旧的 refresh token 和它对应的 access token 都会被记录到数据库黑名单中
    'BLACKLIST_AFTER_ROTATION': True,  # 启用黑名单（需 migrate）
    'UPDATE_LAST_LOGIN': True,
    'BLACKLIST_TOKEN_CHECKS': ['rest_framework_simplejwt.token_blacklist.validators.BlacklistValidator'],
}

ROOT_URLCONF = 'user_web_server.urls'

# 自定义用户模型
AUTH_USER_MODEL = 'accounts.CustomUser'


SITE_ID = 1
LOGIN_REDIRECT_URL = '/'  # 登录成功后跳转的页面
# 指定要使用的登录方法(用户名、电子邮件地址两者之一) # username_email
ACCOUNT_LOGIN_METHODS = {'username'}
# 要求用户注册时要填写的字段，*号为必填项
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*', 'password2*']

# 注册中邮件验证方法: "强制(mandatory)"、 "可选(optional)" 或 "否(none)" 之一 ,(注册成功后，会发送一封验证邮件，用户必须验证邮箱后，才能登陆)
ACCOUNT_EMAIL_VERIFICATION ="none"
ACCOUNT_RATE_LIMITS = {  # 最多验证次数
    'confirm_email': '5/m',  # 5次/分钟，或你可以自定义冷却逻辑
}
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS =3 # 邮箱验证的过期时间，单位为天，默认为 3 天

AUTHENTICATION_BACKENDS = [
    # 用于 Admin 和原生认证
    'django.contrib.auth.backends.ModelBackend',

    # allauth 前台登录支持
    'allauth.account.auth_backends.AuthenticationBackend',
]

TEMPLATES = [  # 网站的模板配置
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # 全局 (公共)模板目录
        'APP_DIRS': True, #  Django 会自动去每个已注册 App 里找 templates/ 子目录
        'OPTIONS': {
            # Django 会在渲染任何模板前，依次调用这些函数，把它们返回的字典合并到你的上下文中
            # 这样你就能在模板里引用这些变量，例如 user,messages, request等常用的上下文变量
            'context_processors': [
                'django.template.context_processors.request', # `allauth` needs this from django
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '123',
            'secret': '456',
            'key': ''
        }
    }
}

WSGI_APPLICATION = 'user_web_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'  # 时区

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'  # 网站项目的静态资源
# 这是用户上传的媒体文件
MEDIA_URL = '/media/' # 媒体文件访问的URL前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 相当于存储位置是 项目的media文件夹下

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
