# Generated by Django 5.2.6 on 2025-09-13 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=20, verbose_name='昵称')),
                ('avatar', models.ImageField(upload_to='avatar', verbose_name='头像')),
                ('sex', models.CharField(choices=[('m', '男'), ('f', '女')], max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('signature', models.CharField(max_length=500, verbose_name='性格')),
                ('hobby', models.CharField(blank=True, max_length=500, verbose_name='爱好')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '角色资料',
                'verbose_name_plural': '角色资料',
            },
        ),
    ]
