# Generated by Django 5.2.6 on 2025-09-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='agent_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='昵称'),
        ),
    ]
