# Generated by Django 5.2.6 on 2025-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agentprofile_age_alter_agentprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='character_setting',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='人设'),
        ),
    ]
