# Generated by Django 5.2.6 on 2025-09-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_agentprofile_age_alter_agentprofile_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否软删除'),
        ),
    ]
